# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Blow-Server CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 3) 환경변수 파일 생성
    - name: make application.properties 파일 생성
      run: |
        ## create application.yml
        cd ./src/main
        mkdir resources
        cd resources

        # application.yml 파일 생성
        touch ./application.yml

        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.BLOW_DEV_APPLICATION }}" >> ./application.yml
        
        # application.yml 파일 확인
        cat ./application.yml

        
        cd ./src/main/resources

        mkdir -p src/main/resources/firebase

        cd ./src/main/resources/firebase

        touch ./blow-31a43-firebase-adminsdk-pacsd-19008fc544.json

        echo "${{ secrets.FCM_SECRET }}" >> ./blow-31a43-firebase-adminsdk-pacsd-19008fc544.json
        
      shell: bash
        
    # 이 워크플로우는 gradle build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle # 실제 application build(-x 옵션을 통해 test는 제외)
      run: ./gradlew build -x test
